### ISSUE TITLE
Remove Radiation_Model submodule

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/ebtelPlusPlus#34]
The Radiation_Model submodule was added with the intention of adding the full-radiative loss function at some point. There's really no need for this and including this large chunk of code is more effort than it is worth, especially since so little of it is used here. 

The Radiation_Model submodule should be removed and replaced with a single function which computes the radiative loss rate from the power-law.

**Comment by jwreep** [comment]
With this update, in the configuration file, the following line seems redundant:

`<use_power_law_radiative_losses>True</use_power_law_radiative_losses>`  

Perhaps remove it?

**Comment by wtbarnes** [comment]
Yeah I'm not sure why it got left in in the first place and I've been meaning to get around to pulling it out. See #45

**Comment by jwreep** [comment]
Ah, I should pay more attention to the open issues.  Thanks.
