### ISSUE TITLE
Change boost install instructions

### ISSUE THREAD

**Issue by schonfsj** [rice-solar-physics/ebtelPlusPlus#46]
I just installed and compiled ebtel++ and had one issue with the instructions provided at http://rice-solar-physics.github.io/ebtelPlusPlus/ related to installing boost. Specifically, the libraries weren't being found when I went to run `scons`. Manually changing the paths as suggested didn't help because I didn't have the libraries at all. I ended up resolving this by running `sudo apt-get install libboost-all-dev` which also downloaded the libraries. After that, `scons` ran without needing to set the paths manually. You might want to suggest this more complete install in that document.

Note: It's likely that this issue is unique to my setup. I'm running Ubuntu 18.04.01 in the Windows Subsystem for Linux (WSL) which has a very bare-bones initial OS install

**Comment by wtbarnes** [comment]
Sorry for just now responding to this old issue! Thanks for the suggestion. I've always struggled to find a general set of instructions for installing boost. It seems to be slightly different on each OS and even different versions of linux. I need to update the install instructions in several places so I will take this into account when I do
