### ISSUE TITLE
Scons doesn't work

### ISSUE THREAD

**Issue by BrandonGel** [rice-solar-physics/ebtelPlusPlus#60]
Hello,
Scons doesn't seem to run on my Anaconda.  I'm not sure what to do.  I downloaded all the necessary libraries.  I'm using Window with Cygwin64.   
---------------------------------------------------------------------
When running the SConstruct file, I get this error:

C:\Users\brand\ebtelPlusPlus>scons --includepath=/usr/local/include --libpath=/usr/local/lib
scons: Reading SConscript files ...
Unrecognized platform. Using Windows compile options.

scons: *** An executable should have exactly one target with the suffix: .exe
File "C:\Users\brand\ebtelPlusPlus\SConstruct", line 64, in <module>

---------------------------------------------------------------------
Then I changed the following line in SConstruct:
env.Program('bin/ebtel++', allobjs)
to
env.Program('bin/ebtel++', allobjs)
env['PROGSUFFIX'] = '.run'
Then I get this error:

C:\Users\brand\ebtelPlusPlus>scons --includepath=/usr/local/include --libpath=/usr/local/lib
scons: Reading SConscript files ...
Unrecognized platform. Using Windows compile options.
scons: done reading SConscript files.
scons: Building targets ...
g++ /Forsp_toolkit\source\file.obj /c rsp_toolkit\source\file.cpp -std=c++11 -O3 /nologo /IC:\usr\local\include
'g++' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [rsp_toolkit\source\file.obj] Error 1
scons: building terminated because of errors.

---------------------------------------------------------------------
Finally, I changed the following line in SConstruct:
env = Environment(CXX=CXX, CXXFLAGS=cxx_flags)
to
PATH = {'PATH' : ['C:/cygwin64/bin']}
env = Environment(ENV = PATH,CXX=CXX, CXXFLAGS=cxx_flags)
Then I get this error:

C:\Users\brand\ebtelPlusPlus>scons --includepath=/usr/local/include --libpath=/usr/local/lib
scons: Reading SConscript files ...
Unrecognized platform. Using Windows compile options.
scons: done reading SConscript files.
scons: Building targets ...
g++ /Forsp_toolkit\source\file.obj /c rsp_toolkit\source\file.cpp -std=c++11 -O3 /nologo /IC:\usr\local\include
g++: error: /Forsp_toolkit\source\file.obj: No such file or directory
g++: error: /c: No such file or directory
g++: error: /nologo: No such file or directory
g++: error: /IC:\usr\local\include: No such file or directory
scons: *** [rsp_toolkit\source\file.obj] Error 1
scons: building terminated because of errors.

**Comment by wtbarnes** [comment]
It appears that somehow the path to the rsp_toolkit submodule is getting mangled and it can't find it. When you cloned the repo, did you use the `--recursive` option to get all the submodules? One way to check this is whether the `rsp-toolkit` repo is empty or not. 

Also, this comment may be useful regarding getting things working with a conda installation of scons/boost: https://github.com/rice-solar-physics/ebtelPlusPlus/issues/41#issuecomment-575252938.

There may be other complications running this on Windows with cygwin. I know others have been able to compile run ebtel++ on Windows, but I've only used this on macOS and Linux (both with and without conda).

**Comment by BrandonGel** [comment]
My rsp-toolkit repo is not empty.  I have these files.
![image](https://user-images.githubusercontent.com/34258122/124181062-0c7cab80-da83-11eb-86c5-b526274c411d.png)

**Comment by wtbarnes** [comment]
Ok that's good. 

My comment regarding the mangled filename is because of these lines,
```
g++ /Forsp_toolkit\source\file.obj /c rsp_toolkit\source\file.cpp -std=c++11 -O3 /nologo /IC:\usr\local\include
g++: error: /Forsp_toolkit\source\file.obj: No such file or directory
```

Do you know why it is prepending the filepath with a `/Fo`? It seems like it can't find the stuff in `rsp_toolkit` because the path to that submodule is being mangled for some reason.

**Comment by BrandonGel** [comment]
I'm not sure at all.

**Comment by wtbarnes** [comment]
I've significantly simplified the installation process which I hope will mitigate this issue (though I still don't fully understand the underlying problem) so I'm going to close this issue. Feel free to reopen if you're still encountering this problem.
