### ISSUE TITLE
Low temperature

### ISSUE THREAD

**Issue by biswajitmb** [rice-solar-physics/ebtelPlusPlus#62]
Hi,

I am very new to ebtel/ebtel++ and trying to do a loop model by using it. 
I found that the temperature during the end of the flare in example-2  (given within the package), is going below the background temperature.  Please find the attachment to see it visually. Here I have increased the initial background heating time to show the background temperature (dashed horizontal black line).

Is it physical, if the background heating is continuously applying during the whole period of the flare? If so please let me know the reason behind it. Or it is due to some numerical problem or I am missing something in my understanding of continuous background heating.

Thanks!
Biswajit
[ex1.pdf](https://github.com/rice-solar-physics/ebtelPlusPlus/files/6973441/ex1.pdf)

**Comment by wtbarnes** [comment]
Hi Biswajit. Yes, I believe this is physical. When radiative cooling takes over (following the peak in the density, where conductive cooling and radiative cooling balance one another, it can cause the temperature to "overshoot" the equilibrium temperature (as determined by the constant background heating). If you extend the time of the example simulation (say out to 10^4 s), you should see the temperature evolution recover the equilibrium temperature (i.e. the blue curve should lie on top of your dashed black line).

**Comment by biswajitmb** [comment]
Thank you! It is reasonable to me. After playing with it, initially, I realized that it could be due to the faster radiation cooling and checked it by multiplying a lower value with the scaling law used within "loop.cpp". In this case, the temperature/pressure was not going below the constant background.

Can you please mention, how can I get the estimated conductive flux and radiative loss throughout the simulation in an easy way?

**Comment by wtbarnes** [comment]
These can be optionally output by the simulation by setting the `save_terms` variable in the config file to `True`. See http://rice-solar-physics.github.io/ebtelPlusPlus/configuration/. This should output a `.terms` file that has heat_flux, c_1, and the radiative losses as a function of time.

**Comment by biswajitmb** [comment]
Great! this is working and fulfills my requirement. Thank you a lot! 
I am closing the issue here.
