### ISSUE TITLE
Estimate average DEM

### ISSUE THREAD

**Issue by biswajitmb** [rice-solar-physics/ebtelPlusPlus#63]
Hi,

I am trying to estimate the average DEM for a loop, which is constructed with multiple strands (e.g, 100 numbers). In my setup, the simulation time is fixed for each strand and running the model multiple times (~100) to see the dynamics of the evolution of the whole loop. In the end, I want to estimate the transition region and coronal DEM for the whole loop. I think a simple average of the DEMs for all the 100 strands will not give me the average DEM for the loop as it depends on the density square. I think, 1st I have to store the density and temperature evolution of each strand, and then after taking the average of them, I have to estimate the average DEM for the whole loop. In this case, can I use the inbuild dem routine? If yes, how can I use it? Or it could be estimated in another way?

Thanks!
Biswajit

**Comment by wtbarnes** [comment]
Sorry for the delayed response here. 

I think the answer here depends on what you want to assume about the strands comprising your loop, both when it comes to the geometry of the loop and the temperature distribution across the loop.

In the built-in DEM routines, for the coronal DEM, at each timestep, emission is spread over some "coronal" temperature range (that is calculated at each timestep according to the temperature at that timestep) (see https://github.com/rice-solar-physics/ebtelPlusPlus/blob/5bd26f4aa386aca8c8589d540b1e98c0dc1f6975/source/dem.cpp#L54). The transition region case is a bit more complicated but is explained in the appendix of this paper: https://ui.adsabs.harvard.edu/abs/2008ApJ...682.1351K/abstract. In both cases, the end result is a 2D array with dimensions corresponding to time and temperature and the assumption is that the loop is all contained along a single line of sight. A common technique is to time average this DEM and to think of this as an average over many loops all at different phases of their evolution.

Alternatively, you could take the the square of the density of each one of your loop simulations at each timestep, bin these in temperature (according to the same coronal temperature range mentioned above or just using the value of the temperature at that timestep) and then time average that. This would be for a coronal DEM though. I do not believe that this would work for the transition region and the built-in approach is likely more valid.

I hope that is helpful. In short, I think the answer is there is not one "right way" to do this and it all depends on how many assumptions you want to make and how much complexity you want to add.

**Comment by biswajitmb** [comment]
Thanks for your comments.

I agree with you that the estimation of TR DEM is non-trivial. 
I found that the average value of the coronal DEM for all the loops and that of estimated from the density array provides a similar results. Thus I have used the 1st technique that you mentioned.

**Comment by wtbarnes** [comment]
Great! Glad you were able to sort it out.
