### ISSUE TITLE
Free-free emission in radiative losses?

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/ebtelPlusPlus#83]
The code has this comment:
```
// NOTE: free-free radiation is included in the parameter values for log_10 T > 7.63
```
Is f-f radiation **_not_** included at lower temperatures in the power law fit?  If so, why?  It should be non-negligible down to much lower temperatures.

**Comment by wtbarnes** [comment]
Good point. I copied the power-law radiative loss function straight from HYDRAD which also includes this comment: https://github.com/rice-solar-physics/HYDRAD/blob/0fa1f9949540e6b9379548c72a030621fdee381d/Radiation_Model/source/radiation.cpp#L712 so I would pass that question on to @sjbradshaw.

My assumption was that the continuum is included in that power-law approximation everywhere but that it dominates at $\log{T}>7.63$. Here's a plot that shows a comparison between the RK loss (the one used here) and the radiative losses from CHIANTI that include the continuum contribution:

<img width="594" alt="image" src="https://github.com/rice-solar-physics/ebtelPlusPlus/assets/8676141/da17183e-cffc-4bc6-b4a9-3c25e1426e1c">

Naively, it appears that the component > 7.63 is specifically constructed to mimic the dominant continuum component at those high temperatures.

**Comment by sjbradshaw** [comment]
The power-law radiation function in HYDRAD includes the free-free (continuum) emission at the highest temperatures (> log T = 7.63). So, this will also be what is used in EBTEL++.

 

[FYI: The HYDRAD radiation code also includes a separate function to calculate just the free-free emission, which is added to the line emission calculated ion-by-ion for (e.g.) non-equilibrium radiation, in the appropriate temperature range.]

 

Hope this helps.

 

Cheers,

 

Steve

**Comment by jwreep** [comment]
Does that mean HYDRAD neglects free-free for lower temperatures when using power law losses?

**Comment by sjbradshaw** [comment]
The power-law losses are just a fit to a (presumably) fairly detailed calculation of radiative losses. So, if those original calculations included free-free at lower temperatures then the power-law losses will too; if not, then no.

**Comment by wtbarnes** [comment]
I'm going to close this because at the very least, I think this is out of scope for ebtel++. Feel free to reopen if you think there are still questions that need to be answered.
