### ISSUE TITLE
Recent versions of boost requiring C++14 ?

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/ebtelPlusPlus#89]
Installing and building on my laptop (Mac M3) with a fresh install, and ran into errors with `boost`.  (Possibly due to updates to `boost`?)

Lots of errors similar to this:
```
g++ -o source/main.o -c -std=c++11 -O3 -I/opt/local/include -I/usr/include/malloc -I/opt/homebrew/include source/main.cpp
In file included from source/main.cpp:8:
In file included from /opt/homebrew/include/boost/numeric/odeint.hpp:27:
In file included from /opt/homebrew/include/boost/numeric/odeint/stepper/euler.hpp:23:
/opt/homebrew/include/boost/numeric/odeint/stepper/base/explicit_stepper_base.hpp:165:42: error: 'auto' not allowed in lambda parameter
        m_resizer.adjust_size(in, [this](auto&& arg) { return this->resize_impl<StateIn>(std::forward<decltype(arg)>(arg)); });
                                         ^~~~
```

The error is due to `SConstruct` defining `-std=c++11`, and can be fixed by setting to `-std=c++14`.  [See this thread.](https://stackoverflow.com/questions/48653124/why-is-auto-not-allowed-in-lambda-parameter)

I know that the plan is to migrate away from `scons`, but this is really an issue with `boost`.  I think future installs might need to pin the C++ version (or the `boost` version, or both).

**Comment by wtbarnes** [comment]
#81 (to be merged very soon, for real!) includes a fix to the SConstruct that pins to C++-14. Does that fix solve your particular issue? I could pull that commit out of that PR and merge it in separately if that's helpful.

**Comment by jwreep** [comment]
Ah, thank you Will.  I didn't know this had already been noticed.  I've edited my local copy already so no worries there, but perhaps for the upcoming paper it would be good to have this merged prior to submission (whether that's #81 or a separate PR).

**Comment by wtbarnes** [comment]
If I don't merge that PR in the next few days (I've been working on it a bit recently), I'll pull out that commit and merge it separately so we have it.

**Comment by jwreep** [comment]
Thank you!
